---
Name: simple-content-elements
---
SCEExtension:
  remove_content_field: true
SCETextImage:
  image_width: 400
  image_height: 300
  image_mode: 'Fill'
SCEImage:
  image_width: 1024
  image_height: 400
  image_mode: 'PaddedImage'
SCEDescribedImages_Image:
  image_width: 400
  image_height: 300
  image_mode: 'Fill'